version: '2'
services:
  mysql:
    # image: registry.cn-hangzhou.aliyuncs.com/forntlogs/frontlogsql
    build: .
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456